using System;

[Serializable]
public struct HiddenAttributes
{
    // All values 0–20 (hidden from player).
    // Generated by AbilitySystem; higher PA → higher floor on average.
    public int LearningRate;    // 0-20: scales training progress rate
    public int WorkEthic;       // 0-20: speed driver; multiplies work output per tick
    public int Adaptability;    // 0-20: versatility; higher values reduce the off-role work penalty
                                //        and narrow the XP gap between primary and spillover skills
    public int Ambition;        // 0-20: self-worth awareness; primary driver of salary demands
    public int Creative;        // 0-20: creative thinking; drives quality output on all contracts
}
