public static class CandidateExpiryHelper
{
    // Fallback defaults — used when no TuningConfig is provided
    private const int AutoGeneratedExpiryDays = 15;
    private const int HRSourcedExpiryDays = 20;
    private const float UrgencyMediumThreshold = 0.50f;
    private const float UrgencyHighThreshold   = 0.25f;

    public static void AssignExpiryTicks(EmployeeState employeeState, IRng rng, int currentTick,
        TuningConfig tuning = null)
    {
        int autoExpiry = tuning != null ? tuning.CandidateAutoExpiryDays : AutoGeneratedExpiryDays;
        int hrExpiry   = tuning != null ? tuning.CandidateHRExpiryDays   : HRSourcedExpiryDays;

        int count = employeeState.availableCandidates.Count;
        for (int i = 0; i < count; i++)
        {
            var candidate = employeeState.availableCandidates[i];
            int baseDays = candidate.IsTargeted ? hrExpiry : autoExpiry;
            int windowTicks = baseDays * TimeState.TicksPerDay;

            if (candidate.ExpiryTick <= 0 || candidate.ExpiryTick < currentTick)
            {
                int varianceTicks = rng.Range(0, TimeState.TicksPerDay);
                candidate.ExpiryTick = currentTick + windowTicks + varianceTicks;
            }
        }
    }

    public static void TickExpiryTimers(EmployeeState employeeState, InterviewSystem interviewSystem,
        NegotiationSystem negotiationSystem, int currentTick, System.Collections.Generic.List<int> expiredIds)
    {
        int count = employeeState.availableCandidates.Count;
        for (int i = 0; i < count; i++)
        {
            var candidate = employeeState.availableCandidates[i];
            if (candidate.ExpiryTick <= 0) continue;

            bool isPaused = false;
            if (interviewSystem != null)
            {
                bool inInterview = interviewSystem.IsInterviewInProgress(candidate.CandidateId);
                bool midFunnel = candidate.InterviewStage > 0 && candidate.InterviewStage < 3;
                if (inInterview || midFunnel) isPaused = true;
            }
            if (!isPaused && negotiationSystem != null && negotiationSystem.HasActiveNegotiation(candidate.CandidateId))
                isPaused = true;

            candidate.IsTimerPaused = isPaused;
            if (isPaused)
            {
                candidate.ExpiryTick += TimeState.TicksPerDay;
            }
            else if (currentTick >= candidate.ExpiryTick)
            {
                expiredIds.Add(candidate.CandidateId);
            }
        }

        int expiredCount = expiredIds.Count;
        for (int e = 0; e < expiredCount; e++)
        {
            int expiredId = expiredIds[e];
            for (int i = employeeState.availableCandidates.Count - 1; i >= 0; i--)
            {
                if (employeeState.availableCandidates[i].CandidateId == expiredId)
                {
                    employeeState.availableCandidates.RemoveAt(i);
                    break;
                }
            }
        }
    }

    public static string GetUrgencyDisplay(EmployeeState employeeState, int candidateId, int currentTick,
        TuningConfig tuning = null)
    {
        float percent = GetTimeRemainingPercent(employeeState, candidateId, currentTick, tuning);
        float medThreshold = tuning != null ? tuning.CandidateUrgencyMediumThreshold : UrgencyMediumThreshold;
        float highThreshold = tuning != null ? tuning.CandidateUrgencyHighThreshold  : UrgencyHighThreshold;
        if (percent < 0f)            return "Plenty of time";
        if (percent > medThreshold)  return "Plenty of time";
        if (percent > highThreshold) return "Considering offers";
        return "Likely leaving soon";
    }

    public static float GetTimeRemainingPercent(EmployeeState employeeState, int candidateId, int currentTick,
        TuningConfig tuning = null)
    {
        CandidateData candidate = FindCandidate(employeeState, candidateId);
        if (candidate == null) return -1f;
        if (candidate.ExpiryTick <= 0) return 1f;

        int autoExpiry = tuning != null ? tuning.CandidateAutoExpiryDays : AutoGeneratedExpiryDays;
        int hrExpiry   = tuning != null ? tuning.CandidateHRExpiryDays   : HRSourcedExpiryDays;
        int baseDays = candidate.IsTargeted ? hrExpiry : autoExpiry;
        int totalTicks = baseDays * TimeState.TicksPerDay;
        if (totalTicks <= 0) return 1f;

        int remaining = candidate.ExpiryTick - currentTick;
        if (remaining < 0) remaining = 0;

        return (float)remaining / totalTicks;
    }

    private static CandidateData FindCandidate(EmployeeState employeeState, int candidateId)
    {
        int count = employeeState.availableCandidates.Count;
        for (int i = 0; i < count; i++)
        {
            if (employeeState.availableCandidates[i].CandidateId == candidateId)
                return employeeState.availableCandidates[i];
        }
        return null;
    }
}
